name: kide
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.1
  provider: ^4.0.2
  flutter_staggered_grid_view: ^0.3.0
  url_launcher: ^5.4.1
  shared_preferences: ^0.5.4+6
  flutter_launcher_icons: ^0.7.4
  google_maps_flutter: ^0.5.11
  geolocator: ^5.1.4+2
  permission_handler: '^4.2.0+hotfix.3'
  cloud_firestore: ^0.13.0+1
  connectivity: ^0.4.6+2
  location: ^2.3.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "./lib/assets/Icon/kide_logoxxxhdpi.png"

flutter:
  uses-material-design: true
  
  assets:
   - ./lib/assets/event.jpg
   - ./lib/pages/EventsPage/assets/time.svg
   - ./lib/pages/EventsPage/assets/bookmark.svg
   - ./lib/assets/fire.svg
   - ./lib/assets/police.svg
   - ./lib/assets/pharmacy.svg
   - ./lib/assets/maps.jpg
   - ./lib/assets/maps.png
   - ./lib/assets/Icon/kide_logoxxxhdpi.png
   - ./lib/assets/Icon/kide_logoldpi.png
   - ./lib/assets/Icon/kide_logo.svg
   - ./lib/assets/Icon/kide_logo_bottom.svg
   - ./lib/assets/contact.jpg
   - ./lib/assets/contact.png
   - ./lib/assets/events.jpg
   - ./lib/assets/events.png
   - ./lib/pages/HomePage/assets/KIUG_KIIT.jpg
   - ./lib/assets/KIIT.jpg
   - ./lib/assets/KISS.png
   - ./lib/assets/Founder_sir.jpeg