name: Kide
description: A KIIT guide you'd want to use.
version: 1.0.3+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.1
  provider: ^4.0.2
  flutter_staggered_grid_view: ^0.3.0
  url_launcher: ^5.4.1
  shared_preferences: ^0.5.4+6
  google_maps_flutter: ^0.5.11
  geolocator: ^5.1.4+2
  permission_handler: '^4.2.0+hotfix.3'
  cloud_firestore: ^0.13.0+1
  connectivity: ^0.4.6+2
  location: ^2.3.5
  transparent_image: ^1.0.0
  
dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "./lib/assets/Icon/kide_logoxxxhdpi.png"

flutter:
  uses-material-design: true
  
  assets:
   - ./lib/assets/fire.svg #
   - ./lib/assets/police.svg #
   - ./lib/assets/pharmacy.svg #
   - ./lib/assets/Icon/kide_logoldpi.png #
   - ./lib/assets/Icon/kide_logoxxxhdpi.png #
   - ./lib/assets/maps.png #
   - ./lib/assets/contact.png #
   - ./lib/assets/AOG-Logo.png
   - ./lib/assets/events.png
   - ./lib/assets/KIIT.jpg
   - ./lib/assets/KISS.png #
   - ./lib/assets/Founder_sir.jpeg #